reponame: github.com/untangle/openwrt
description: |
  MFW fork of openwrt/openwrt, with minimal patches
users:
  maintainers:
    - sdelafond@arista.com
    - jsommerville@arista.com
x-bar:
  version: production
epoch: 1
